services: 
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - data:/var/lib/registry:rw
      - ./config.yaml:/etc/docker/registry/config.yml:ro

volumes:
  data:
