services:
  mqtt-server:
    image: eclipse-mosquitto:latest
    container_name: mqtt-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - data:/mosquitto/data
      - logs:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - mqtt

volumes:
  data:
  logs:

networks:
  mqtt:
