services:
  nginx:
    image: nginx:alpine
    container_name: "${HOST_NAME}"
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=${HOST_NAME}
      - LETSENCRYPT_HOST=${HOST_NAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${HTTP_ROOT}:/usr/share/nginx/html:ro
      - cache:/var/cache:rw
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  cache:
