services:
  app:
    container_name: pano-server
    build: .
    ports:
      - "${PORT}:3000"
    volumes:
      - "${PANO_ROOT}:/app/public
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - "VIRTUAL_HOST=${HOST_NAME}"
      - "VIRTUAL_PORT=${PORT}
      - "LETSENCRYPT_HOST=${HOST_NAME}"
      - "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"
    networks:
      - proxy

networks:
  reverse:
    external: true
