services:
  app:
    container_name: "${HOST_NAME}"
    build: .
    expose:
      - "80:3000"
    volumes:
      - "${PANO_ROOT}:/app/public"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - "VIRTUAL_HOST=${HOST_NAME}"
      - "LETSENCRYPT_HOST=${HOST_NAME}"
      - "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"
    networks:
      - proxy

networks:
  proxy:
    external: true
