services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "443:443"
      - "81:80"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./etc:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./etc:/etc/nginx/vhost.d:rw
      - ./html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "NGINX_PROXY_CONTAINER=nginx-proxy"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
