services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    container_name: kuma
    ports:
      - 3001:3001
    volumes:
      - data:/app/data

volumes:
  data:

networks:
  kuma: